
- name: Check if Keypair Exists
  stat:
    path: /etc/ansible/roles/usermgmt/files/{{ org.employees[item.name].name }}
  with_items:
    - "{{ org.environments[ENV].members }}"
  register: result
  tags:
    - key_mgmt

- name: Ensure SSH key is generated
  command: ssh-keygen -t rsa -f /etc/ansible/roles/usermgmt/files/{{ org.employees[item.name].name }} -C {{ org.employees[item.name].name }} -q -N ""
  args:
    creates: /etc/ansible/roles/usermgmt/files/{{ org.employees[item.name].name }}
  with_items:
    - "{{ org.environments[ENV].members }}"
  check_mode: no
#  when: result.stat.exists == False
  tags:
    - key_mgmt
