- name: Allow 'devops' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%devops'
    line: '%devops ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  become: yes
  tags:
    - user_mgmt

- name: Allow 'devlead' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%devlead'
    line: '%devlead ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  become: yes
  tags:
    - user_mgmt

- name: Add group
  group:
    name:  "{{item.name}}"
    state: '{{item.gstate | default("present")}}'
  with_items: "{{usergroups}}"
  become: yes
  tags:
    - user_mgmt

- name: Add user
  user:
    name: "{{org.employees[item.name].name }}"
    state: "{{org.employees[item.name].state }}"
    shell: /bin/bash
    groups: "{{ item.group }}"
  with_items:
    - "{{ org.environments[ENV].members }}"
  become: yes
  tags:
    - user_mgmt

- name: Add keys
  authorized_key:
    user: "{{ org.employees[item.name].name }}"
    key: "{{ lookup('file', '{{ org.employees[item.name].name }}.pub') }}"
  with_items:
    - "{{ org.environments[ENV].members }}"
  when: '"{{ org.employees[item.name].state }}" == "present"'
  become: yes
  tags:
    - user_mgmt

- name: Remove user folder
  file:
    state: absent
    path: "/home/{{ item.name }}/"
  with_items:
    - "{{ org.environments[ENV].members }}"
  when: '"{{ org.employees[item.name].state }}" == "absent"'
  become: yes
  tags:
    - user_mgmt
